# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'production-monitor'

# Load and evaluate rules in this file every  gc'evaluation_interval' seconds.
rule_files:
  - "alert.rules_some_metric"
#   - "alert.rules_nodes"
#   - "alert.rules_containers"
#   - "alert.rules_container-groups"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # - job_name: 'cloudwatch-exporter'
  #   scrape_interval: 15s
  #   scrape_timeout: 15s
  #   static_configs:
  #     - targets: ['localhost:9106']
  #       labels:
  #         "region": "us-east-1"

  # - job_name: 'node'
  #   scrape_interval: 10s
  #   scrape_timeout: 5s
  #   static_configs:
  #     - targets: ['node-exporter:9100', ]

  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   scrape_timeout: 5s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['pushgateway:9091']

  # - job_name: 'telegraf'
  #   scrape_interval: 10s
  #   scrape_timeout: 5s
  #   static_configs:
  #     - targets: ['telegraf:9273']

  # - job_name: 'containers'
  #   scrape_interval: 10s
  #   scrape_timeout: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # # - job_name: 'repositories'
  # #   scrape_interval: 10s
  # #   scrape_timeout: 5s
  # #   static_configs:
  # #     - targets: ['github-exporter:9171']

   - job_name: 'prometheus'
     scrape_interval: 10s
     scrape_timeout: 5s
     static_configs:
       - targets: ['localhost:9090']

   - job_name: 'aws_ce'
     scrape_interval: 10s
     scrape_timeout: 5s
     static_configs:
       - targets: ['aws_ce:1234']
# Alerting specifies settings related to the Alertmanager.
# alerting:
#   # alert_relabel_configs:
#   #   [ - <relabel_config> ... ]
#   alertmanagers:
#     - static_configs:
#       - targets: ["alertmanager:9093"]

remote_read:
  - url: 'http://influxdb:8086/api/v1/prom/read?u=admin&p=admin&db=awc_ce'
remote_write:
  - url: 'http://influxdb:8086/api/v1/prom/write?u=admin&p=admin&db=awc_ce'
